# Generated by Django 6.0.7 on 2026-08-05 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='เลขที่คำร้อง')),
                ('start_datetime', models.CharField(max_length=100, verbose_name='วันที่ยืม')),
                ('end_datetime', models.CharField(max_length=100, verbose_name='กำหนดส่งคืน')),
                ('purpose', models.TextField(verbose_name='วัตถุประสงค์')),
                ('location', models.CharField(max_length=255, verbose_name='สถานที่นำไปใช้')),
                ('pickup_method', models.CharField(max_length=100, verbose_name='ช่องทางการรับอุปกรณ์')),
                ('status', models.CharField(choices=[('รอการอนุมัติ', 'รอการอนุมัติ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('รอตรวจสอบการคืน', 'รอตรวจสอบการคืน'), ('คืนไม่ครบ', 'คืนไม่ครบ'), ('คืนสำเร็จ', 'คืนสำเร็จ'), ('เกินกำหนด', 'เกินกำหนด')], default='รอการอนุมัติ', max_length=30, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างคำร้อง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอยืม')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='borrow_app.borrowrequest')),
            ],
        ),
    ]
