# Generated by Django 6.0.7 on 2026-08-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสอุปกรณ์/เลขครุภัณฑ์')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่ออุปกรณ์')),
                ('category', models.CharField(max_length=100, verbose_name='หมวดหมู่')),
                ('status', models.CharField(default='พร้อมให้ยืม', max_length=50, verbose_name='สถานะอุปกรณ์')),
                ('is_bundle', models.BooleanField(default=False, verbose_name='เป็นชุด Bundle')),
            ],
        ),
    ]
