# Generated by Django 6.0.7 on 2026-08-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0002_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrow_app.equipment', verbose_name='อุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
