# Generated by Django 6.0.7 on 2026-08-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0003_borrowitem_equipment_alter_borrowitem_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipments/'),
        ),
    ]
