# Generated by Django 6.0.7 on 2026-08-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0004_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='acquisition_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='วันที่ได้มา (acquisitionDate)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='acquisition_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='วิธีได้มา (acquisitionMethod)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='amount_posted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='มูลค่า (amountPosted)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_no_main',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสหลัก (assetNoMain)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_no_sub',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสย่อย (assetNoSub)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='available_quantity',
            field=models.IntegerField(default=1, verbose_name='จำนวนคงเหลือ'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='count_result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผลการตรวจนับ'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='funding_source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='แหล่งเงิน (fundingSource)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='holder_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสผู้ถือครอง'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='holder_department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='หน่วยงาน (holderDepartment)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='holder_dept_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสหน่วยงาน'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='holder_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ผู้ถือครอง (holderName)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขบาร์โค้ด/Serial (inventoryNo)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_count_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ปีที่นับล่าสุด'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตข้อมูลล่าสุด'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='seq_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับ (seqNo)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_quantity',
            field=models.IntegerField(default=1, verbose_name='จำนวนทั้งหมด (quantity)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(max_length=100, verbose_name='หมวดหมู่ (equipmentCategory)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='รหัสอุปกรณ์/เลขครุภัณฑ์'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่ออุปกรณ์ (assetDescription)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('พร้อมให้ยืม', 'พร้อมให้ยืม'), ('กำลังถูกยืม', 'กำลังถูกยืม'), ('อยู่ระหว่างซ่อม', 'อยู่ระหว่างซ่อม'), ('ชำรุด', 'ชำรุด')], default='พร้อมให้ยืม', max_length=50, verbose_name='สถานะอุปกรณ์'),
        ),
    ]
