# Generated by Django 6.0.7 on 2026-08-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0005_equipment_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุการคืน'),
        ),
    ]
