# Generated by Django 6.0.7 on 2026-08-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0006_borrowrequest_return_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_determ', models.CharField(max_length=255, verbose_name='accountDeterm / หมวดหมู่')),
                ('asset_description', models.CharField(max_length=255, verbose_name='assetDescription / ประเภท')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_group_images/', verbose_name='รูปภาพหมวดหมู่')),
            ],
            options={
                'verbose_name': 'หมวด/ประเภทอุปกรณ์',
                'verbose_name_plural': 'หมวด/ประเภทอุปกรณ์',
                'unique_together': {('account_determ', 'asset_description')},
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='borrow_app.equipmentgroup', verbose_name='หมวด/ประเภทอุปกรณ์'),
        ),
    ]
