# Generated by Django 6.0.7 on 2026-08-07 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0007_equipmentgroup_equipment_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับคืน'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ไม่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='return_evidence/', verbose_name='รูปหลักฐานการคืน'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืน'),
        ),
    ]
