# Generated by Django 6.0.7 on 2026-08-07 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0008_borrowrequest_approved_by_borrowrequest_received_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='end_datetime',
            field=models.DateField(blank=True, null=True, verbose_name='กำหนดส่งคืน'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='start_datetime',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ยืม'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='ข้อความ')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrow_app.borrowrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
