# Generated by Django 6.0.7 on 2026-08-07 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0009_alter_borrowrequest_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowitem',
            name='requested_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมวดหมู่ที่ขอยืม'),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrow_app.equipment', verbose_name='อุปกรณ์ที่จัดสรร'),
        ),
    ]
