# Generated by Django 6.0.7 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0010_borrowitem_requested_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_incomplete_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ความเห็นกรณีคืนไม่ครบ'),
        ),
    ]
