# Generated by Django 6.0.7 on 2026-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0010_borrowitem_requested_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowitem',
            name='return_status',
            field=models.CharField(default='ยังไม่คืน', max_length=50),
        ),
    ]
