# Generated by Django 6.0.7 on 2026-08-10 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0011_borrowrequest_return_incomplete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowitem',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_borrow_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='return_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด'), ('สูญหาย', 'สูญหาย')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='return_status',
            field=models.CharField(choices=[('ยังไม่คืน', 'ยังไม่คืน'), ('รอตรวจรับ', 'รอตรวจรับ'), ('ตรวจรับแล้ว', 'ตรวจรับแล้ว')], default='ยังไม่คืน', max_length=20),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('พร้อมให้ยืม', 'พร้อมให้ยืม'), ('กำลังถูกยืม', 'กำลังถูกยืม'), ('อยู่ระหว่างซ่อม', 'อยู่ระหว่างซ่อม'), ('ชำรุด', 'ชำรุด'), ('สูญหาย', 'สูญหาย')], default='พร้อมให้ยืม', max_length=50, verbose_name='สถานะอุปกรณ์'),
        ),
    ]
