# Generated by Django 6.0.7 on 2026-08-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0013_alter_equipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowitem',
            name='received_by',
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_comment',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุการคืนรายชิ้น'),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด'), ('สูญหาย', 'สูญหาย')], max_length=50, null=True, verbose_name='สภาพอุปกรณ์ตอนคืน'),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_status',
            field=models.CharField(choices=[('ยังไม่คืน', 'ยังไม่คืน'), ('รอตรวจรับ', 'รอตรวจรับ'), ('คืนแล้ว', 'คืนแล้ว'), ('ชำรุด', 'ชำรุด'), ('สูญหาย', 'สูญหาย')], default='ยังไม่คืน', max_length=50, verbose_name='สถานะการคืนรายชิ้น'),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืนรายการนี้'),
        ),
    ]
