# Generated by Django 6.0.7 on 2026-08-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0011_borrowitem_return_status'),
        ('borrow_app', '0014_remove_borrowitem_received_by_and_more'),
    ]

    operations = [
    ]
