# Generated by Django 6.0.7 on 2026-08-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0015_merge_20260811_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowitem',
            name='return_status',
            field=models.CharField(choices=[('ยังไม่คืน', 'ยังไม่คืน'), ('รอตรวจรับ', 'รอตรวจรับ'), ('คืนแล้ว', 'คืนแล้ว'), ('ชำรุด', 'ชำรุด'), ('สูญหาย', 'สูญหาย')], default='ยังไม่คืน', max_length=50, verbose_name='สถานะการคืนรายชิ้น'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
    ]
