# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0016_alter_borrowitem_return_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(
                choices=[
                    ('พร้อมให้ยืม', 'พร้อมให้ยืม'),
                    ('กำลังถูกยืม', 'กำลังถูกยืม'),
                    ('อยู่ระหว่างซ่อม', 'อยู่ระหว่างซ่อม'),
                    ('ชำรุด', 'ชำรุด'),
                    ('สูญหาย', 'สูญหาย'),
                ],
                default='พร้อมให้ยืม',
                max_length=50,
                verbose_name='สถานะอุปกรณ์',
            ),
        ),
    ]
