# Generated by Django 6.0.7 on 2026-08-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0017_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='pickup_image',
            field=models.ImageField(blank=True, null=True, upload_to='pickup_evidence/%Y/%m/%d/', verbose_name='รูปหลักฐานการรับอุปกรณ์ (ก่อนยืม)'),
        ),
    ]
