# Generated by Django 6.0.7 on 2026-08-17 07:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0018_borrowrequest_pickup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพอุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='equipmentgroup',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพหมวดหมู่'),
        ),
    ]
