# Generated by Django 6.0.7 on 2026-08-17 07:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0019_alter_equipment_image_alter_equipmentgroup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='pickup_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปหลักฐานการรับอุปกรณ์ (ก่อนยืม)'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='return_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปหลักฐานการคืน'),
        ),
    ]
