# Generated by Django 6.0.7 on 2026-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0020_alter_borrowrequest_pickup_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('รอการอนุมัติ', 'รอการอนุมัติ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('ยกเลิก', 'ยกเลิก'), ('รอตรวจสอบการคืน', 'รอตรวจสอบการคืน'), ('คืนไม่ครบ', 'คืนไม่ครบ'), ('คืนสำเร็จ', 'คืนสำเร็จ'), ('เกินกำหนด', 'เกินกำหนด')], default='รอการอนุมัติ', max_length=30, verbose_name='สถานะ'),
        ),
    ]
