# Generated by Django 6.0.7 on 2026-08-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_app', '0021_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='กำหนดส่งคืน'),
        ),
    ]
